apiVersion: v2
name: giropops-senhas
description: Chart for the giropops senhas application
version: 0.1.0 # chart version
appVersion: 1.0 # application version
sources:
  - https://github.com/badtuxx/giropops-senhas
